apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: fr
  name: fr
spec:
  replicas: 1
  selector:
    matchLabels:
      run: fr
  template:
    metadata:
      labels:
        run: fr
    spec:
      containers:
      - image: thkrebs/fr_services:latest
        name: fr